name: pop_path
description: App Flutter per calcolo distanza, dislivello e posizione GPS

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map_location_marker: ^8.0.3
  geolocator: ^10.1.0
  share_plus: ^7.2.1
  latlong2: ^0.9.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6
  fl_chart: ^0.64.0
  shared_preferences: ^2.1.1
  flutter_map: ^6.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

dependency_overrides:
  win32: 3.0.1
